name: GIFPlayer
options:
  bundleIdPrefix: com.tolgaugurlu
  deploymentTarget:
    macOS: 14.0
targets:
  GIFPlayer:
    type: application
    platform: macOS
    sources:
      - GIFPlayer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tolgaugurlu.gifplayer
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024 Tolga Uğurlu. Tüm hakları saklıdır."
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: GIFPlayer/GIFPlayer.entitlements
    info:
      path: GIFPlayer/Info.plist
      properties:
        CFBundleName: GIF Player
        CFBundleDisplayName: GIF Player
        LSApplicationCategoryType: public.app-category.graphics-design
        NSHighResolutionCapable: true 